---
name: Update APIs
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - bash_aliases
      - '*.Dockerfile'
      - .github/workflows/update.yml

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Decrypt environment file
        run: docker-compose -f docker-compose.ci.yml run --rm decrypt-env
        env:
          ENV_PASSWORD: ${{ secrets.env_file_encryption_key }}
      - name: Unit tests
        run: docker-compose run --rm unit
  update-serverless-functions:
    runs-on: ubuntu-latest
    needs:
      - unit-tests
    steps:
      - uses: actions/checkout@v1
      - name: Decrypt environment file
        run: docker-compose -f docker-compose.ci.yml run --rm decrypt-env
        env:
          ENV_PASSWORD: ${{ secrets.env_file_encryption_key }}
      - name: Deploy serverless functions
        run: scripts/deploy
        env:
          ENVIRONMENT: production
