---
name: Update my status
on:
  push:
    paths:
      - '!*/**'
      - '.github/workflows/update.yml'
  schedule:
  - cron: '*/15 * * * *'

jobs:
  update_status:
    runs-on: ubuntu-latest
    steps:
      - name: Perform status updates
        run: >-
          file=$(mktemp);
          code=$(curl -X POST -H 'X-API-Key: ${{ secrets.status_api_key }}' \
            -o "$file" -w '%{http_code}' '${{ secrets.status_url }}');
          body=$(cat "$file");
          rm -f "$file";
          if [ "$code" != 200 ];
          then \
            >&2 echo "ERROR: Update failed with [$code]: $body";
            exit 1;
          fi;

