---
name: Update my status
on:
  schedule:
  - cron: '*/15 * * * *'

jobs:
  update_status:
    runs-on: ubuntu-latest
    steps:
      - name: Perform status updates
        run: curl -X POST -H "X-API-Key: ${{ secrets.status_api_key }}" "${{ secrets.status_url }}"
